kind: Template
apiVersion: v1
metadata:
  name: "apiman-sidekick"
  annotations:
    description: "Sidekick Api publisher"
    iconClass: "icon-load-balancer"
    tags: "api,gateway,apiman,sidekick,api-discovery"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${name}"
    labels:
      app: "${name}"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: "${name}"
      spec:
        containers:
          - name: sidekick
            image: docker.io/jcechace/apiman-sidekick
            imagePullPolicy: Always
            env:
            - name: APIMAN_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "${APIMAN_NAME}-auth-secret"
                  key: "APIMAN_AUTH_USERNAME"
            - name: APIMAN_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${APIMAN_NAME}-auth-secret"
                  key: "APIMAN_AUTH_PASSWORD"
    test: false

parameters:
- name: "name"
  description: "Name of the example service"
  value: "apiman-sidekick"
- name: APIMAN_NAME
  description: "Name of the Apiman API Gateway"
  value: apiman